### ISSUE TITLE
Permission setting

### ISSUE THREAD

**Issue by sbd0517** [adamint/ArdentKotlin#1]
Developers of Ardent,
    Thank you for bringing this powerful and efficient bot! It works perfectly well in our server and helps to entertainment many visitors in it.
    A mere issue we face when operating the bot is that our visitors, who are unauthorized to manage the server, cannot use the DJ functions of Ardent freely. We noted your consideration of potential risk for full access to DJ commands by all visitors; however, in most of the cases our visitors are good-minded and will not cause troubles by using commands like "pause" or "stop" or by queuing over one songs. Since low-rank visitors do not have access to these functions, our administrators, who are of a small number, are busying helping our visitors by making commands.
    Can you help us with this issue? Maybe by teaching us how to change the permission setting (if this is changeable in the current version) or setting up a new command for us to allow visitor to gain access to most DJ functions.
    Best Regards, Fine Shao

**Comment by adamint** [comment]
Hey, thanks for being so thorough. When I was first developing music, I provided support for this in the form of users and roles with "advanced permissions". However, I forgot to make a setting to modify the people with this access inside Discord, which is now making me facepalm. I'll go ahead and do this now, and will close this issue once it's complete.

**Comment by adamint** [comment]
This is now added with /settings - look for the "trusteveryone" setting

**Comment by sbd0517** [comment]
It really amazes us that you responded so quickly to our need!!! We can't be more grateful. Thank you! The new setting works fine, which allows our visitors to stop the Ardent by themselves.
But still, our visitors are not allowed to queue over one song (except by playing a Youtube playlist.) Through "/settings current", we noticed that there exists a parameter called "Add more than 1 song at a time for normal users" and the default is "false", but we could not figure out the command to change this parameter.
Sorry for bothering you once more, but we really need this fixed ><

**Comment by adamint** [comment]
It's really not a problem! The original goal was to have the web panel up by now so that you'd have access to changing this setting immediately, but we got delayed 😞; after I saw your issue, I ended up implementing these settings inside Discord (a bit more hastily than I would've liked but nothing I can do). 

Anyways, I rethought and ended up removing the setting - and committed the change. However, you won't see changes for a few hours, when I'll update and restart the bot, as I prefer to space out restarts. If you have any more issues, questions, or comments, feel free to join the Ardent server, where I, along with the other administrators, will be able to reply much faster @ https://discord.gg/pMEV8t6
